branch-defaults:
  main:
    environment: test
    group_suffix: null
environment-defaults:
  test:
    branch: null
    repository: null
global:
  application_name: mc2-pleasure-api
  branch: null
  default_ec2_keyname: mc2-pleasure
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
