# Generated by Django 4.2 on 2023-05-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='applemusic_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='artwork_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
